FROM node:8.9.4-alpine

MAINTAINER soar <85624529@qq.com>

RUN apk update && apk upgrade && \
    apk add --no-cache unzip && \
    apk add --no-cache bash git openssh && \
    npm install pm2@2.1.4 -g
